export const GET_MEALS_LOADING = 'GET_MEALS_LOADING';
export const GET_MEALS_SUCCESS = 'GET_MEALS_SUCCESS';
export const GET_MEALS_ERROR = 'GET_MEALS_ERROR';

export const GET_MEAL_LOADING = 'GET_MEAL_LOADING';
export const GET_MEAL_SUCCESS = 'GET_MEAL_SUCCESS';
export const GET_MEAL_ERROR = 'GET_MEAL_ERROR';

export const ADD_AND_DELETE_MEAL_IN_FAVORITE = 'ADD_AND_DELETE_MEAL_IN_FAVORITE';
export const GET_FAVORITE = 'GET_FAVORITE';

export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const SET_USER = "SET_USER"
